### ISSUE TITLE
Project not participating in hacktoberfest 2021

### ISSUE THREAD

**Issue by akanshSirohi** [Ayush7614/CheatSheet-Templates#39]
![image](https://user-images.githubusercontent.com/34837239/136086375-3e5e6929-0e21-496e-8bdf-ed828024da4c.png)
Can someone please explain me this...??

**Comment by Ayush7614** [comment]
What are you doing this take some time when it is update it will show matures so please wait and dont do this from next time you are directly blindly open issues for your query
